[tool.poetry]
name = "blog-ai"
version = "0.1.0"
description = ""
authors = ["Lorenzo"]
license = "GNU General Public License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
